### ISSUE TITLE
32 bit build?

### ISSUE THREAD

**Issue by xloem** [clickot/ungoogled-chromium-build#2]
It’s hard to find 32 bit chromium builds. Google has v2.33 downloadable 32 bit. Snap has version 98 for 32 bit. Any chance of an appimage?

**Comment by clickot** [comment]
dear @xloem , i'm sorry but i do not have a 32 bit build procedure and i won't develop one (a single build of chromium takes about 8h, and since I do not have a 32bit system at hand, i won't be even be able to test it properly). 
I hope for your understanding that that is a bit too much effort for me...
